# Generated by Django 2.1.4 on 2018-12-26 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Createur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('indication', models.CharField(max_length=300, null=True)),
                ('degre_urgence', models.CharField(choices=[('H24', 'H24'), ('immédiat', 'immédiat'), ('48H', '48H'), ('72H', '72H'), ('1_semaine', '1_semaine')], max_length=10)),
                ('type_examen', models.CharField(choices=[('scanner cerebral', 'scanner cerebral'), ('scanner AP', 'scanner AP'), ('scanner TAP', 'scanner TAP'), ('angioscanner pulmonaire', 'angioscanner pulmonaire'), ('uroscanner', 'uroscanner'), ('scanner Thoracique', 'scanner thoracique')], max_length=30)),
                ('injection', models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('à discuter', 'à discuter')], max_length=30)),
                ('realisation', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default='non', max_length=30, null=True)),
                ('validation_choix', models.CharField(choices=[('accepter', 'accepter'), ('refuser', 'refuser'), ('accepter sous condition', 'accepter sous condition'), ('demander un rappel', 'demander un rappel')], max_length=30, null=True)),
                ('suppression', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default='non', max_length=10, null=True)),
                ('heure', models.DateTimeField(null=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Demandes.Createur')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(default='', max_length=10000, null=True)),
                ('regionAnatomique', models.CharField(default='', max_length=10000, null=True)),
                ('geste', models.CharField(default='non', max_length=3, null=True)),
                ('intitule', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('statut', models.CharField(choices=[('radiologue', 'radiologue'), ('prescripteur', 'prescripteur'), ('secretaire', 'secretaire')], max_length=30, null=True)),
                ('examens', models.ManyToManyField(to='Demandes.Examen')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Radiologue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=30, null=True)),
                ('nom', models.CharField(max_length=30, null=True)),
                ('indisponibilites', models.CharField(max_length=1000, null=True)),
                ('statut', models.CharField(choices=[('praticien clinicien', 'praticien clinicien'), ('praticien hospitalier', 'praticien hospitalier'), ('interne', 'interne')], max_length=30, null=True)),
                ('tempsDeTravail', models.CharField(choices=[('1/2 temps', '1/2 temps'), ('3/4 temps', '3/4 temps'), ('temps complet', 'temps complet')], max_length=30, null=True)),
                ('vacationFixe', models.CharField(max_length=1000, null=True)),
                ('jourSansTravail', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Validant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='validant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Demandes.Validant'),
        ),
    ]
