# Generated by Django 2.1.5 on 2019-02-10 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Demandes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='regionAnatomique',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='geste',
        ),
        migrations.AddField(
            model_name='examen',
            name='realisant',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
