# Generated by Django 2.1.5 on 2019-02-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demandes', '0002_auto_20190210_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='validationRequise',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
