# Generated by Django 2.1.5 on 2019-03-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demandes', '0003_examen_validationrequise'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='commentaires',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
