# Generated by Django 2.1.5 on 2019-03-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demandes', '0004_demande_commentaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='commentaires',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
