# Generated by Django 2.1.5 on 2019-03-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demandes', '0005_examen_commentaires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='commentaires',
            new_name='commentaire',
        ),
    ]
